version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "whom-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qxwgr0rd8z5p"
s3_prefix = "whom-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
